### ISSUE TITLE
Typo in the match_chain() documentation

### ISSUE THREAD

**Issue by ctreffe** [jobrachem/alfred3-interact#27]
There is a typo in the example of the [match_chain() function](https://alfredo3.psych.bio.uni-goettingen.de/interact-docs/generated/alfred3_interact.match.MatchMaker.match_chain.html) in the documentation:

```python
@exp.member
class Match(ali.WaitingPage):

    def wait_for(self):
        group = self.exp.plugins.mm.match_chain(spec2=3*60, spec2=None)
        self.exp.plugins.group = group
        self.exp.condition = group.data.spec_name
        return True
```

I believe the line with the call to match_chain() should read `group = self.exp.plugins.mm.match_chain(spec2=3*60, spec1=None)` to make sense, right? There should not be two mentions of _spec2_, I think.

**Comment by jobrachem** [comment]
Yep, you‘re totally right!
