### ISSUE TITLE
Matchmaker quota does not handle expiration correctly

### ISSUE THREAD

**Issue by jobrachem** [jobrachem/alfred3-interact#33]

**Comment by jobrachem** [comment]
@ctreffe I think I need a more detailed description of the issue. In my tests, I currently cannot reproduce an issue. What I'm doing is this:

1. Start an experiment session with 1 second timeout
  - Match it to role "a" in a group in a `SequentialSpec("a", "b", nslots=1, name="test")`
  - Wait for 1 second
  - Verify that the session is indeed expired and not aborted (because there was no movement after expiration)
2. Start a second experiment session
  - Match the second session, again, to a `SequentialSpec("a", "b", nslots=1, name="test")`
  - Verify that the second session takes role "a" in the same group
3. Start a third experiment session
  - Match the third session, again, to a `SequentialSpec("a", "b", nslots=1, name="test")`
  - Verify that the third session is aborted, because the spec is currently full.

Everything seems to work as expected for me.

**Comment by ctreffe** [comment]
Hey @jobrachem, thank you for testing this. I have run some additional tests and can confirm that the match maker is working as expected regarding the handling of session timeouts. I erroneously assumend that the match maker would check other sessions in the slot list against the timeout setting of its own parent session. However, the match maker uses the timeout settings from the queried datasets.

In my case, this leads to a problem with incomplete sessions in which no JavaScript was executed at the session start (usually, this happend when an experiment is called from something else than a browser, which will prevent the javascript on an experiment's first page from being executed). These sessions generate data sets, but any changes made to the session_timeout in the setup hook are not saved to these data sets. Hence, I have many sessions with the default timeout of 24 hours in my data. These sessions clog the match maker, which is the origin of the problems I reported earlier.

As a possible solution to this, maybe we could load the default session timeout from the config.conf, to allow users to change the default at the earliest possible time?

**Comment by jobrachem** [comment]
See https://github.com/ctreffe/alfred/issues/212
