### ISSUE TITLE
WaitingPage: wait_timeout_page and wait_exception_page can not be defined as class attributes

### ISSUE THREAD

**Issue by ctreffe** [jobrachem/alfred3-interact#36]
Contrary to the documentation, defining wait_timeout_page and wait_exception_page as class attributes is overwritten in the __init__ function of the WaitingPage class. 

We should add a check whether the class attribute has been set before overwriting both arguments with default pages.

**Comment by jobrachem** [comment]
Good catch! What a silly bug. I just pushed a commit and made a new release to pypi.
